CAMERA_X = 3
CAMERA_Y = 1
CAMERA_Z = 0
CENTER_X = 0
CENTER_Y = 0
CENTER_Z = -0.275
DEFAULT_COLOURBAR_POS = 0.75
DEFAULT_ZOOM = 1.89
FILENAME = "cheetah.off"
REGION_COLOURBAR_POS = 0.72
REGION_ZOOM = 2.63
UPSAMPLE = 0
XMAX = inf
XMIN = 0.7
YMAX = -0.8
YMIN = -inf
ZMAX = inf
ZMIN = 8
