CAMERA_X = 2
CAMERA_Y = 1
CAMERA_Z = 0
CENTER_X = 0.27
CENTER_Y = 0
CENTER_Z = -0.08
DEFAULT_COLOURBAR_POS = 0.98
DEFAULT_ZOOM = 1.49
FILENAME = "bird.off"
REGION_COLOURBAR_POS = 0.98
REGION_ZOOM = 2.2
UPSAMPLE = 1
XMAX = inf
XMIN = 0.18
YMAX = 0.06
YMIN = -inf
ZMAX = 0.28
ZMIN = -0.88
